
language: objective-c
os: osx
osx_image: xcode8.3
before_install:
    - rvm use system
    - sudo gem install cocoapods
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean -workspace V2EX.xcworkspace -scheme V2EX | xcpretty
  - xcodebuild -workspace V2EX.xcworkspace -scheme V2EX -configuration Release -destination generic/platform=iOS | xcpretty -s
  