
language: objective-c
os: osx
osx_image: xcode8.3
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod repo update
script:
  - export LC_CTYPE=en_US.UTF-8
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean -workspace V2EX.xcworkspace -scheme V2EX | xcpretty
  - xcodebuild -workspace V2EX.xcworkspace -scheme V2EX -configuration Release -destination generic/platform=iOS | xcpretty -s
  